git submodule add https://github.com/nitrogenjs/service.git
git submodule add https://github.com/nitrogenjs/client.git
git submodule add https://github.com/nitrogenjs/devices.git
git submodule add https://github.com/nitrogenjs/admin.git
git submodule add https://github.com/nitrogenjs/camera.git
git submodule add https://github.com/nitrogenjs/devops.git
git submodule add https://github.com/nitrogenjs/commands.git
git submodule add https://github.com/nitrogenjs/reactor.git
git submodule add https://github.com/nitrogenjs/stores.git
git submodule add https://github.com/nitrogenjs/cli.git
git submodule add https://github.com/nitrogenjs/apps.git
git submodule add https://github.com/nitrogenjs/website.git